name: Coveralls

on:
  push:
  pull_request:
  release:
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: "Coveralls with ROOT 6.28.04 17"
    runs-on: ubuntu-latest

    steps:
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install common dependencies
        run: |
          sudo apt update
          sudo apt install cmake wget libgtest-dev lcov -y
          sudo apt install python3-numpy libtbb-dev libxxhash0 -y
          cmake --version
          wget http://gccb.if.uj.edu.pl/code/root-cpp17_6.28.04_amd64.deb
          sudo dpkg -i root-cpp17_6.28.04_amd64.deb

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14.0
        with:
          cmake-version: latest

      - name: Configure
        env:
          CFLAGS: -fprofile-arcs -ftest-coverage
          CXXFLAGS: -fprofile-arcs -ftest-coverage
          LDFLAGS: -lgcov
        shell: bash
        run: |
          . /etc/profile
          root-config --version
          root-config --cflags
          root-config --features
          mkdir build
          cd build
          cmake .. \
            -DHelloFitty_DEVELOPER_MODE=ON \
            -DBUILD_TESTING=ON \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir

      - name: Build
        shell: bash
        run: |
            cd build
            make

      - name: Test
        shell: bash
        run: |
            cd build
            make test

      - name: Examples
        shell: bash
        run: |
          build/example/example1   # first try
          build/example/example1   # second try
          build/example/example2 build/example/test_hist.root build/example/test_input.txt build/example/results2.root
          build/example/example2 build/example/test_hist.root build/example/test_input.txt build/example/results2.root

      - name: lcov-action
        uses: danielealbano/lcov-action@v3
        with:
          remove_patterns: build,examples,tests
          build_dir: build

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: coverage.info
